<script type="text/javascript" src="{{ asset('template2/assets/js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/tether.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/jquery-migrate.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/hidemaxlistitem.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/jquery-ui.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/hidemaxlistitem.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/jquery.easing.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/scrollup.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/jquery.waypoints.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/waypoints-sticky.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/pace.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/slick.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/scripts.js') }}"></script>